export const PROMISE = 'PROMISE';

export const START_LOADING_BOOK = 'START_LOADING_BOOK';
export const SUCCESS_LOADING_BOOK = 'SUCCESS_LOADING_BOOK';
export const FAILURE_LOADING_BOOK = 'FAILURE_LOADING_BOOK';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const OPEN_TOC = 'OPEN_TOC';
export const CLOSE_TOC = 'CLOSE_TOC';

export const APPEND_ITEM_PAGES = 'APPEND_ITEM_PAGES';
export const RESET_PAGES = 'RESET_PAGES';
export const CHANGE_ACTIVE_PAGE = 'CHANGE_ACTIVE_PAGE';

export const ADD_LOADED_POSITION = 'ADD_LOADED_POSITION';
export const RESET_LOADED_POSITION = 'RESET_LOADED_POSITION';

export const START_LOADING_LAST_POSITION = 'START_LOADING_LAST_POSITION';
export const SUCCESS_LOADING_LAST_POSITION = 'SUCCESS_LOADING_LAST_POSITION';
export const FAILURE_LOADING_LAST_POSITION = 'FAILURE_LOADING_LAST_POSITION';